name: dend_capstone
channels:
  - defaults
dependencies:
  - python=3.7
  - google-cloud-bigquery=1.24.0
  - jupyter_core=4.6.1
  - boto3=1.12.0
  - pandas-gbq=0.13.1
  - xlrd=1.2.0
  - psycopg2=2.8.4
  - s3fs=0.4.0
  - seaborn=0.10.0